CREATE TABLE CUSTOMER(
ID BIGSERIAL NOT NULL,
FIRST_NAME VARCHAR(22) NOT NULL,
LAST_NAME VARCHAR(22) NOT NULL,
AGE BIGINT,
PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT(
ID BIGSERIAL NOT NULL,
NAME VARCHAR(22) NOT NULL,
PRICE DECIMAL NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE PURCHASE(
CUSTOMER_ID BIGINT  NOT NULL,
PRODUCT_ID BIGINT NOT NULL,
AMOUNT BIGINT NOT NULL,
PURCHASE_DATE TIMESTAMP NOT NULL,
PRIMARY KEY (CUSTOMER_ID, PRODUCT_ID, PURCHASE_DATE)
);
