INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Andrew', 'Lawlor', 23);

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Test', 'Name', 17);

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Peter', 'Lawlor', 21);

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Customer', 'Four', 99);