INSERT INTO PURCHASE (CUSTOMER_ID, PRODUCT_ID, AMOUNT, PURCHASE_DATE)
VALUES (1, 1, 5, CURRENT_TIMESTAMP);

INSERT INTO PURCHASE (CUSTOMER_ID, PRODUCT_ID, AMOUNT, PURCHASE_DATE)
VALUES (1, 2, 10, CURRENT_TIMESTAMP);

INSERT INTO PURCHASE (CUSTOMER_ID, PRODUCT_ID, AMOUNT, PURCHASE_DATE)
VALUES (1, 3, 100, CURRENT_TIMESTAMP);